# Generated by Django 2.0.2 on 2018-08-14 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('event_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='事件id')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '预警事件',
                'verbose_name_plural': '预警事件',
            },
        ),
        migrations.CreateModel(
            name='AlertInfo',
            fields=[
                ('info_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('message', models.TextField(verbose_name='信息内容')),
                ('time_frame_type', models.CharField(choices=[(1, 'minutes'), (2, 'hours'), (3, 'days')], max_length=10, verbose_name='检测时间段类型')),
                ('time_frame_num', models.IntegerField(verbose_name='检测时间段长度')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '预警事件基本信息',
                'verbose_name_plural': '预警事件基本信息',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('rule_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='规则id')),
                ('alert_type', models.CharField(choices=[(1, 'minutes'), (2, 'hours')], max_length=10, verbose_name='警告类型')),
                ('address', models.CharField(max_length=50, verbose_name='联系方式')),
                ('numevents', models.IntegerField(verbose_name='更新时间')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.AlertInfo', verbose_name='预警事件基本信息')),
            ],
            options={
                'verbose_name': '预警具体规则',
                'verbose_name_plural': '预警具体规则',
            },
        ),
        migrations.AddField(
            model_name='alertevent',
            name='info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alert.AlertInfo', verbose_name='预警事件基本信息'),
        ),
    ]
