# Generated by Django 2.0.2 on 2018-08-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertevent',
            old_name='time',
            new_name='hit_time',
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='numevents',
            field=models.IntegerField(verbose_name='命中数'),
        ),
    ]
