# Generated by Django 2.0.2 on 2018-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20180816_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertevent',
            old_name='info_id',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='alertrule',
            old_name='info_id',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='事件id'),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='info_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='rule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
