# Generated by Django 2.0.7 on 2018-08-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_auto_20180816_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertevent',
            old_name='info',
            new_name='info_id',
        ),
        migrations.RenameField(
            model_name='alertrule',
            old_name='info',
            new_name='info_id',
        ),
    ]
