# Generated by Django 2.0.2 on 2018-08-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_auto_20180817_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.AlertInfo', verbose_name='预警事件基本信息'),
        ),
    ]
